<?php

/**
 * Implementation of hook_og_mailinglist_save_node_alter().
 */
function og_mailinglist_og_forum_og_mailinglist_save_node_alter(&$node) {
  // If this is a forum post and the og_forum module is enabled, find this group's
  // default forum container and add that to the node object.
  if ($node->type == "forum" && module_exists('og_forum')) {
    $forum_id = db_result(db_query("SELECT tid
                                    FROM {og_term}
                                    WHERE nid = %d
                                    AND public <> 0", current($node->og_groups)));
    $term = taxonomy_get_term($forum_id);
    if(empty($node->tid)) {
      $node->tid = $term->tid;
    }
    if(empty($node->vid)) {
      $node->vid = $term->vid;
    }
  }
}

